#include "main.h"
#include "stm32f042x6.h"
#include "stm32f0xx_hal.h"
#include "stm32f0xx_hal_def.h"
#include "stm32f0xx_hal_iwdg.h"
#include "stm32f0xx_hal_tim.h"
#include "stm32f0xx_hal_uart.h"
#include "app.h"
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sys/_intsup.h>

// Handles generated by CubeMX in main.c
extern IWDG_HandleTypeDef hiwdg;
extern TIM_HandleTypeDef htim3;
extern UART_HandleTypeDef huart1;

// Tunable timings (in milliseconds)
#define QUALIFY_MS              5u    // inputs healthy this long before 'o' allowed
#define PRECHARGE_MIN_MS        5u    // ignore handover condition before this
#define PRECHARGE_TIMEOUT_MS    100u  // nominal ~20 ms for 2 mF; fault if exceeded
#define HANDOVER_OVERLAP_MS     5u    // CCEN and PREEN both on before PREEN drops
#define HEARTBEAT_MS            250u  // LED toggle, normal      
#define HEARTBEAT_FAULT_MS      80u   // LED toggle, faulted (fast blink)
#define TELEMETRY_MS            500u  // periodic status line

// Fast pin acess functions (for single-cycle register operations)
static inline bool pin_high(GPIO_TypeDef *port, uint16_t pin) { return (port->IDR & pin) != 0u; }
static inline void pin_set (GPIO_TypeDef *port, uint16_t pin) { port->BSRR = pin; }
static inline void pin_clr (GPIO_TypeDef *port, uint16_t pin) { port->BRR  = pin; }

/*
   Comparator polarity
 
   Assumed AMC23C14 behaviour (consistent with the U301 design notes):
     OUT1 (adjustable VREF): LOW when input is ABOVE its threshold
     OUT2 (fixed 300 mV)   : HIGH when input is ABOVE its threshold
     Loss of VDD1          : BOTH outputs LOW
 
   U301 input bus : OUT1 = INCMP1 (OV 65.8 V), OUT2 = INCMP2 (UV 48.6 V)
   U302 output bus: OUT1 = OUTCMP1 (~55 V),    OUT2 = OUTCMP2 (~45.2 V)
 
   A dead U302 VDD1 drives OUTCMP1 low, which on its own would read as
   "above 55 V". The handover condition therefore also requires OUTCMP2
   high, which a dead supply can never produce.
 
   Check each macro on the bench with a bench supply before connecting the
   power stage. If a polarity is wrong, flip it here - nowhere else.
*/
#define INPUT_NOT_OV()      ( pin_high(INCMP1_GPIO_Port,  INCMP1_Pin))
#define INPUT_NOT_UV()      ( pin_high(INCMP2_GPIO_Port,  INCMP2_Pin))
#define OUTPUT_ABOVE_55V()  (!pin_high(OUTCMP1_GPIO_Port, OUTCMP1_Pin))
#define OUTPUT_ABOVE_45V()  ( pin_high(OUTCMP2_GPIO_Port, OUTCMP2_Pin))
 
/* TPSI open-drain outputs: FLT1/ALM1 active-low, PGOOD high = supply good */
#define CC_SUPPLY_OK()      ( pin_high(CCPGOOD_GPIO_Port,  CCPGOOD_Pin))
#define PRE_SUPPLY_OK()     ( pin_high(PREPGOOD_GPIO_Port, PREPGOOD_Pin))
#define CC_NO_TRIP()        ( pin_high(CCFLT_GPIO_Port,    CCFLT_Pin))
#define CC_NO_ALARM()       ( pin_high(CCALM_GPIO_Port,    CCALM_Pin))

// State
static volatile relay_state_t   state =         STATE_INIT;
static volatile uint32_t        faults =        0u;
static volatile uint32_t        warnings =      0u;
static volatile uint8_t         pending_cmd =   0u;

static uint8_t  rx_byte;
static char     tx_buf[96];
static const char *last_msg = "BOOT";

static uint32_t  t_state_entry;     // tick when current state was entered
static uint32_t  t_healthy_since;   // tick when inputs last became healthy
static bool      was_healthy;
static uint32_t  t_heartbeat;
static uint32_t  t_telemetry;
static bool      status_due;

static const char *const state_name[] = {
    "INIT", "OFF", "PRECHARGE", "HANDOVER", "ON", "FAULT"
};

// Relay Control

// Open both paths immediately. Safe to call from any context.
static inline void relay_open_all(void)
{
    pin_clr(CCEN_GPIO_Port, CCEN_Pin);
    pin_clr(PREEN_GPIO_Port, PREEN_Pin);
}

static inline bool is_energised(relay_state_t s)
{
    return (s == STATE_PRECHARGE) || (s == STATE_HANDOVER) || (s == STATE_ON);
}

// Called from ISRs: open first, then record.
static inline void trip(uint32_t fault_bit)
{
    relay_open_all();
    faults |= fault_bit;
}

/* 
    Assert an enable pin and change state, but only if no fault is latched.
    ISRs are masked for a few cycles so an ISR cannot latch a fault between
    the check and the pin write.
*/
static bool energise(GPIO_TypeDef *port, uint16_t pin, relay_state_t next)
{
    bool ok;
    __disable_irq();
    ok = (faults == 0u);
    if (ok) {
        state = next;
        pin_set(port, pin);
    }
    __enable_irq();
    return ok;
}

static void enter_state(relay_state_t next)
{
    state = next;
    t_state_entry = HAL_GetTick();
    status_due = true;
}

// Input health
static bool inputs_healthy_now(void)
{
    return  INPUT_NOT_OV() && INPUT_NOT_OV() &&
            CC_SUPPLY_OK() && PRE_SUPPLY_OK() && CC_NO_TRIP();
}

// Debounced: healthy continuously for QUALIFY_MS. Call once per loop.
static bool inputs_qualified(uint32_t now)
{
    if (inputs_healthy_now()) {
        if (!was_healthy) {
            was_healthy = true;
            t_healthy_since = now;
        }
        return (now - t_healthy_since) >= QUALIFY_MS;
    }
    was_healthy = false;
    return false;
}

static uint32_t input_bitmap(void)
{
return  (CC_SUPPLY_OK()                                                 ? (1u << 0) : 0u)
          | (CC_NO_TRIP()                                               ? (1u << 1) : 0u)
          | (PRE_SUPPLY_OK()                                            ? (1u << 2) : 0u)
          | (CC_NO_ALARM()                                              ? (1u << 3) : 0u)
          | (pin_high(INCMP1_GPIO_Port,  INCMP1_Pin)          ? (1u << 4) : 0u)
          | (pin_high(INCMP2_GPIO_Port,  INCMP2_Pin)                    ? (1u << 5) : 0u)
          | (pin_high(OUTCMP1_GPIO_Port, OUTCMP1_Pin)         ? (1u << 6) : 0u)
          | (pin_high(OUTCMP2_GPIO_Port, OUTCMP2_Pin)         ? (1u << 7) : 0u);
}

// Telemetry
static void send_status(void)
{
    if (huart1.gState != HAL_UART_STATE_READY) {
        return;                         // previous line still sending: try next pass
    }
    int n = snprintf(tx_buf, sizeof tx_buf,
                     "ST=%s F=0x%02lX W=0x%02lX IN=0x%02lX EN=%u%u MSG=%s\r\n",
                     state_name[state],
                     (unsigned long)faults,
                     (unsigned long)warnings,
                     (unsigned long)input_bitmap(),
                     pin_high(CCEN_GPIO_Port,  CCEN_Pin)  ? 1u : 0u,
                     pin_high(PREEN_GPIO_Port, PREEN_Pin) ? 1u : 0u,
                     last_msg);
    if (n > 0) {
        if (n >= (int)sizeof tx_buf) { n = (int)sizeof tx_buf - 1; }
        HAL_UART_Transmit_IT(&huart1, (uint8_t *)tx_buf, (uint16_t)n);
        status_due = false;
    }
}

static void send_help(void)
{
    static const char help[] =
        "o=close f=open r=reset s=status | "
        "IN bits: 0 CCPG 1 CCFLT 2 PREPG 3 CCALM 4 INCMP1 5 INCMP2 6 OUTCMP1 7 OUTCMP2\r\n";
    if (huart1.gState == HAL_UART_STATE_READY) {
        HAL_UART_Transmit_IT(&huart1, (uint8_t *)help, (uint16_t)(sizeof help - 1u));
    }
}

// Commands (processed in main loop, never in an ISR)
static void handle_command(uint8_t cmd, bool qualified)
{
    switch (cmd) {
    case 'o':
    case 'O':
        if (state == STATE_FAULT) {
            last_msg = "REJ:FAULTED";
        } else if (state != STATE_OFF) {
            last_msg = "REJ:BUSY";
        } else if (!qualified) {
            last_msg = "REJ:NOT_READY";
        } else if (energise(PREEN_GPIO_Port, PREEN_Pin, STATE_PRECHARGE)) {
            enter_state(STATE_PRECHARGE);
            last_msg = "PRECHARGING";
        } else {
            last_msg = "REJ:FAULTED";
        }
        break;
 
    case 'f':
    case 'F':
        relay_open_all();
        if (state != STATE_FAULT) {
            enter_state(STATE_INIT);        // re-qualify before next close
        }
        last_msg = "OPENED";
        break;
 
    case 'r':
    case 'R':
        if (state != STATE_FAULT) {
            warnings = 0u;
            last_msg = "NO_FAULT";
        } else if (!inputs_healthy_now()) {
            last_msg = "REJ:INPUTS_BAD";
        } else {
            __disable_irq();
            faults   = 0u;
            warnings = 0u;
            __enable_irq();
            enter_state(STATE_INIT);        // re-qualify, stays open
            last_msg = "RESET";
        }
        break;
 
    case '?':
        send_help();
        return;
 
    case 's':
    case 'S':
        break;
 
    default:
        return;                             // ignore line endings etc.
    }
    status_due = true;
}

// Public API
void app_init(void)
{
    // Stop the IWDG counting while halted at a breakpoint (debug only).
    __HAL_RCC_DBGMCU_CLK_ENABLE();
    __HAL_DBGMCU_FREEZE_IWDG();
 
    relay_open_all();
    pin_clr(SCOPE_GPIO_Port, SCOPE_Pin);
 
    uint32_t now   = HAL_GetTick();
    t_state_entry  = now;
    t_heartbeat    = now;
    t_telemetry    = now;
    state          = STATE_INIT;
 
    HAL_TIM_IC_Start_IT(&htim3, TIM_CHANNEL_4);     // OUTCMP2 edges
    HAL_UART_Receive_IT(&huart1, &rx_byte, 1);      // operator commands
 
    last_msg   = "BOOT";
    status_due = true;
}
 
void app_loop(void)
{
    uint32_t now       = HAL_GetTick();
    bool     qualified = inputs_qualified(now);
 
    // ---- Any fault latched by an ISR forces the fault state ----
    if (faults != 0u && state != STATE_FAULT) {
        relay_open_all();
        enter_state(STATE_FAULT);
        last_msg = "TRIPPED";
    }
 
    // ---- Operator command ----
    uint8_t cmd = pending_cmd;
    if (cmd != 0u) {
        pending_cmd = 0u;
        handle_command(cmd, qualified);
    }
 
    // ---- State machine ----
    uint32_t in_state = now - t_state_entry;
 
    switch (state) {
    case STATE_INIT:
        relay_open_all();
        if (qualified) {
            enter_state(STATE_OFF);
            last_msg = "READY";
        }
        break;
 
    case STATE_OFF:
        relay_open_all();
        if (!qualified) {
            enter_state(STATE_INIT);
            last_msg = "NOT_READY";
        }
        break;
 
    case STATE_PRECHARGE:
        if (in_state >= PRECHARGE_MIN_MS && OUTPUT_ABOVE_45V() && OUTPUT_ABOVE_55V()) {
            if (energise(CCEN_GPIO_Port, CCEN_Pin, STATE_HANDOVER)) {
                enter_state(STATE_HANDOVER);
                last_msg = "HANDOVER";
            }
        } else if (in_state > PRECHARGE_TIMEOUT_MS) {
            // Also expected if the input bus is below ~55 V: the fixed
            // OUTCMP1 threshold cannot be reached.
            trip(FAULT_PRECHARGE_TIMEOUT);
        }
        break;
 
    case STATE_HANDOVER:
        if (in_state >= HANDOVER_OVERLAP_MS) {
            pin_clr(PREEN_GPIO_Port, PREEN_Pin);
            enter_state(STATE_ON);
            last_msg = "ON";
        }
        break;
 
    case STATE_ON:
        // Protection is interrupt-driven; nothing to poll here.
        break;
 
    case STATE_FAULT:
        relay_open_all();
        break;
    }
 
    // ---- Watchdog: refreshed only from the loop, every pass ----
    HAL_IWDG_Refresh(&hiwdg);
 
    // ---- Heartbeat LED ----
    uint32_t hb = (state == STATE_FAULT) ? HEARTBEAT_FAULT_MS : HEARTBEAT_MS;
    if ((now - t_heartbeat) >= hb) {
        t_heartbeat = now;
        HAL_GPIO_TogglePin(HEARTBEAT_GPIO_Port, HEARTBEAT_Pin);
    }
 
    // ---- Telemetry ----
    if ((now - t_telemetry) >= TELEMETRY_MS) {
        t_telemetry = now;
        status_due  = true;
    }
    if (status_due) {
        send_status();
    }
}
 
relay_state_t app_get_state(void)    { return state; }
uint32_t      app_get_faults(void)   { return faults; }
uint32_t      app_get_warnings(void) { return warnings; }
 
/*
   Interrupt callbacks (override HAL weak definitions)
   Priority 0 (EXTI, TIM3) - keep them short, no HAL_Delay, no printing.
*/
 
void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
    pin_set(SCOPE_GPIO_Port, SCOPE_Pin);            // latency marker
 
    relay_state_t s = state;
    bool live = is_energised(s);
 
    switch (GPIO_Pin) {
    case CCFLT_Pin:
        if (!CC_NO_TRIP()) {
            relay_open_all();                       // stop TPSI3103 auto-retry
            if (live) { faults |= FAULT_OVERCURRENT; }
        }
        break;
 
    case INCMP1_Pin:
        if (live && !INPUT_NOT_OV()) { trip(FAULT_INPUT_OV); }
        break;
 
    case INCMP2_Pin:
        if (live && !INPUT_NOT_UV()) { trip(FAULT_INPUT_UV); }
        break;
 
    case CCPGOOD_Pin:
        if (live && !CC_SUPPLY_OK()) { trip(FAULT_CC_SUPPLY); }
        break;
 
    case PREPGOOD_Pin:
        if (live && !PRE_SUPPLY_OK()) { trip(FAULT_PRE_SUPPLY); }
        break;
 
    case CCALM_Pin:
        if (!CC_NO_ALARM()) { warnings |= WARN_OC_ALARM; }
        break;
 
    case OUTCMP1_Pin:
        // Handover level is polled in the loop; no action on edges.
        break;
 
    default:
        break;
    }
 
    pin_clr(SCOPE_GPIO_Port, SCOPE_Pin);
}
 
// OUTCMP2 (PB1) arrives via TIM3 CH4 input capture, both edges.
void HAL_TIM_IC_CaptureCallback(TIM_HandleTypeDef *htim)
{
    if (htim->Instance != TIM3 || htim->Channel != HAL_TIM_ACTIVE_CHANNEL_4) {
        return;
    }
    pin_set(SCOPE_GPIO_Port, SCOPE_Pin);
 
    relay_state_t s = state;
    // During PRECHARGE the output is expected to be low; only a drop
    // after handover means the output has collapsed.
    if ((s == STATE_HANDOVER || s == STATE_ON) && !OUTPUT_ABOVE_45V()) {
        trip(FAULT_OUTPUT_COLLAPSE);
    }
 
    pin_clr(SCOPE_GPIO_Port, SCOPE_Pin);
}
 
// USART1 RX: store the byte, re-arm. Processing happens in app_loop().
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    if (huart->Instance == USART1) {
        pending_cmd = rx_byte;
        HAL_UART_Receive_IT(&huart1, &rx_byte, 1);
    }
}
 
// Re-arm reception after an overrun/framing error, otherwise RX stops.
void HAL_UART_ErrorCallback(UART_HandleTypeDef *huart)
{
    if (huart->Instance == USART1) {
        HAL_UART_Receive_IT(&huart1, &rx_byte, 1);
    }
}